### ISSUE TITLE
问一下代码

### ISSUE THREAD

**Issue by ohohohh** [xwmaxwma/rschange#10]
作者您好，我一直找不到代码的模型和文献对应的变化检测以及论文中change extractor，能请问你具体写在哪一个模型的哪个函数里吗？非常感谢

**Comment by xwmaxwma** [comment]
哪个模型？

**Comment by ohohohh** [comment]
![image](https://github.com/user-attachments/assets/14ac910b-8feb-4a7b-a21c-35dbc467bccb)
spixel decode和Detail-enhanced那个代码对应论文图的地方。初学者我找不到非常感谢。
