### ISSUE TITLE
whu_cd

### ISSUE THREAD

**Issue by shizizuoing** [xwmaxwma/rschange#2]
Hello! I would like to recur your code ,Would you mind giving me the WHU-CD dataset you've already processed? My email address is 2481283395@qq.com. Thank you very much!

**Comment by zhanglingyyyyyy** [comment]
作者您好，我需要分析您的论文，能问请您发我一份代码吗，我的邮箱是 [3513685325@qq.com，qq.com]，或者直接发在github上

**Comment by xwmaxwma** [comment]
已更新。有问题随时联系
