### ISSUE TITLE
作者你好在复现代码的时候SENET可以使用但是CMAKER代码出现FileNotFoundError: [Errno 2] No such file or directory: 'rscd/models/backbones/review_pretrain/SeaFormer_L_cls_79.9.pth.tar'

### ISSUE THREAD

**Issue by lixue13** [xwmaxwma/rschange#6]
FileNotFoundError: [Errno 2] No such file or directory: 'rscd/models/backbones/review_pretrain/SeaFormer_L_cls_79.9.pth.tar'出现这个错误，我看配置文件也没有设置他的路径，报这个

**Comment by lixue13** [comment]
只有stnet能运行其他的两个都会出错，是什么原因呢。

**Comment by lixue13** [comment]
这个模型是不是没有开源训练过程

**Comment by xwmaxwma** [comment]
抱歉。backbone预训练权重地址已在seaformer.py文件里更新，可以参考该地址下载。ddlnet的config也已更新。目前能正常训练。我们会在一周内更新其他的模型如BIT，Changeformer等模型的代码以及预训练的权重。目前仓库还有其他问题可联系，会及时修改

**Comment by xwmaxwma** [comment]
已更新
