### ISSUE TITLE
WHU-CD数据集问题

### ISSUE THREAD

**Issue by GaoSheng-RS** [xwmaxwma/rschange#9]
WHU-CD似乎只有训练集和测试集，这个在论文的训练中是怎么处理的？

**Comment by xwmaxwma** [comment]
我们检查了提供的预处理的数据集的链接，WHU-CD有验证集。你是否下载了README中链接所提供的数据集？

**Comment by GaoSheng-RS** [comment]
感谢您的回复，非常抱歉之前是我的疏忽，现在我已经下载了正确的数据集
